services:
  nginx:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    command: ["start-dev"]

    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

volumes:
  keycloak-data: